spring:
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: true
    open-in-view: true
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9095/mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
    h2:
      console:
        enabled: true


logging:
  level:
    org:
      hibernate.type.descriptor.sql.BasicBinder: TRACE
