spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.jdbc.time_zone: UTC
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.generate_statistics: true
    show-sql: true
    open-in-view: true

logging:
  level:
    org:
      hibernate.type.descriptor.sql.BasicBinder: TRACE

jasypt:
  encryptor:
    password: order112!!

jwt:
  key: ENC(xxOAUVk4nQdy+sWgp+I+SLO8dTwOffG6TaHZVbajYo9WGU/xfH2ylw==)
